spring.application.name=RUON
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}


aws.s3.region=${AWS_REGION:ap-northeast-2}
aws.s3.bucket=${AWS_S3_BUCKET:ruon-upload-files}

spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=10MB

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.web.pageable.one-indexed-parameters=true
